# Generated by Django 3.0.2 on 2020-01-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200124_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Sale_rent',
        ),
    ]
