# Generated by Django 3.0.2 on 2020-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
